export enum Role {
  ADMIN = "admin",
  USER = "user",
}

export enum OTPType {
  EMAIL_VERIFY = "EMAIL_VERIFY",
  PASSWORD_RESET = "PASSWORD_RESET",
  VIEW_SHOE = "VIEW_SHOE",
}

export enum AuditAction {
  // auth
  USER_REGISTERED = "USER_REGISTERED",
  USER_LOGGED_IN = "USER_LOGGED_IN",
  USER_LOGGED_OUT = "USER_LOGGED_OUT",
  EMAIL_VERIFIED = "EMAIL_VERIFIED",
  PASSWORD_RESET = "PASSWORD_RESET",
  REFRESH_TOKEN = "REFRESH_TOKEN",
  GET_CURRENT_USER = "GET_CURRENT_USER",

  // shoes
  SHOE_CREATED = "SHOE_CREATED",
  SHOE_UPDATED = "SHOE_UPDATED",
  SHOE_DELETED = "SHOE_DELETED",
  SHOE_VIEWED = "SHOE_VIEWED",

  // purchase
  SHOE_PURCHASED = "SHOE_PURCHASED",
}
